# .github/workflows/client.yml
name: client
on:
  push:
  # 이벤트를 감지할 브랜치
    branches:
      - reference
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Source 단계
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./my-agora-states-client
        
        # Build 단계 
      - name: Build
        run: npm run build
        working-directory: ./my-agora-states-client
        
      - name: SHOW AWS CLI VERSION
        run: aws --version
          
        # S3 Bucket 배포 단계 
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
          
         # AWS CLI 명령어를 입력한다.
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://My-Bucket-Name \ # 빌드 폴더 이름 s3 ://버킷이름
            --delete
        working-directory: ./my-agora-states-client